
# sudo docker-compose -f docker-compose.yml  up -d


version: '3.3'

services:
  postgres-app-huevos:
    image: 'postgres:14'
    restart: always
    network_mode: "host"
    volumes:
      - ./dataDB:/var/lib/postgresql/data
      - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./init-user-db.bash:/docker-entrypoint-initdb.d/init-user-db.bash
    environment:
      PGDATA: /var/lib/postgresql/data/app/
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.UTF-8"
      POSTGRES_USER: augustUser_postgres
      POSTGRES_PASSWORD: augustUser_postgres_pass_2024Sep26
      POSTGRES_DB: apphuevos_db
      PGPORT: 5454
