
# sudo docker-compose -f docker-compose.yml  up -d

version: '3'

services:
  pgadmin4:
      image: elestio/pgadmin:REL-8_12
      restart: always
      network_mode: "host"
      environment:
        PGADMIN_DEFAULT_EMAIL: maacuellarma@gmail.com
        PGADMIN_DEFAULT_PASSWORD: pgadmin
        PGADMIN_LISTEN_PORT: 8080
      ports:
        - "8080:8080"
      volumes:
        - ./servers.json:/pgadmin4/servers.json
